# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
    en: Vincent ROGER's Website
    fr: Site internet de Vincent ROGER
email: roger.vincent.11@gmail.com
description:
    en: PhD student in Machine Learning using Neural Networks technologies on speech in few shot context. Python and Linux enthusiast.
    fr: Thésard en apprentissage machine utilisant les réseaux de neurones artificiels sur de l'audio dans un contexte avec peu de données. Enthousiaste Python et de l'environnement Linux.
index:
    en: index.html
    fr: accueil.html

baseurl: "" # the subpath of your site, e.g. /blog
url: https://vroger11.github.com
twitter_username: vroger11
github_username:  vroger11
linkedin_username: vroger11
repository: vroger11/vroger11.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-github-metadata

disqus:
    shortname: vroger11

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git

