# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
    en: Vincent ROGER
    fr: Vincent ROGER
email: vroger11@protonmail.com
description:
    en: PhD in computer science using machine learning (especially Neural Networks technologies). I work principally on image and audio signals (speech, music, animals and so on). I am a Python programmer and a FOSS enthusiast.
    fr: Docteur en informatique en utilisant l'apprentissage automatique (en particulier les technologies de réseaux neuronaux). Je travaille principalement sur les signaux d'image et audios (parole, musique, animaux, etc.). Je suis un programmeur python et un passionné de logiciels libres.
index:
    en: index.html
    fr: accueil.html

subtitle:
  en: Data and machine learning scientist
  fr: Scientifique des données et de l'apprentissage automatique

baseurl: "" # the subpath of your site, e.g. /blog
url: https://website.vincent-roger.fr
X_username: vroger11
github_username:  vroger11
linkedin_username: vroger11
reddit_username: vroger11
repository: vroger11/vroger11.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  #- jemoji
  - jekyll-github-metadata

disqus:
    shortname: vroger11

feed:
  categories:
    - blog
    - blogue

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git

