name: Build and deploy MkDocs documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Fetch the entire Git history for
          # creation and modification date.
          fetch-depth: 0

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6.8.0
        with:
          # Install a specific version of uv.
          version: "0.8.22"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Deploy to GitHub Pages
        run: |
          uv run mkdocs gh-deploy --force --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
