name: prek

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'

      - uses: j178/prek-action@v1.1.1
